const DB="obra-companion",STORE="projects";let db,PID=null,TAB="resumen",CTX=null;
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),uid=()=>crypto.randomUUID?.()||Date.now()+Math.random(),today=()=>new Date().toISOString().slice(0,10),date=s=>s?new Date(s+"T12:00").toLocaleDateString("es-ES"):"—",eur=n=>Number(n||0).toLocaleString("es-ES",{style:"currency",currency:"EUR"});
function odb(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"id"});r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>no(r.error)})}function os(m="readonly"){return db.transaction(STORE,m).objectStore(STORE)}function all(){return new Promise(ok=>{let r=os().getAll();r.onsuccess=()=>ok(r.result)})}function get(id=PID){return new Promise(ok=>{let r=os().get(id);r.onsuccess=()=>ok(r.result)})}function put(p){p.updated=new Date().toISOString();return new Promise(ok=>{let r=os("readwrite").put(p);r.onsuccess=()=>ok()})}function remove(id){return new Promise(ok=>{let r=os("readwrite").delete(id);r.onsuccess=ok})}
const tabs=["resumen","visitas","incidencias","fotos","mediciones","actas","documentos","costes"];
function f(n,l,t="text",v="",o=[]){if(t==="textarea")return `<div class=field><label>${l}</label><textarea name=${n}>${esc(v)}</textarea></div>`;if(t==="select")return `<div class=field><label>${l}</label><select name=${n}>${o.map(x=>`<option ${x===v?"selected":""}>${x}</option>`).join("")}</select></div>`;return `<div class=field><label>${l}</label><input name=${n} type=${t} value="${esc(v)}" ${t==="number"?'step="0.001"':""}></div>`}
function openForm(title,html,ctx,del=false){CTX=ctx;$("#dlgTitle").textContent=title;$("#fields").innerHTML=html;$("#del").hidden=!del;$("#dlg").showModal()}
async function home(){PID=null;$("#home").hidden=false;$("#project").hidden=true;$("#back").hidden=true;$("#title").textContent="Mis obras";let a=(await all()).sort((x,y)=>y.updated.localeCompare(x.updated));$("#projects").innerHTML=a.map(p=>`<article class=card data-p="${p.id}"><span class=badge>${esc(p.type)}</span><h3>${esc(p.name)}</h3><p>${esc(p.address)}</p><div class=meta>${p.issues.filter(i=>i.status!=="Verificada").length} incidencias abiertas · ${p.visits.length} visitas</div></article>`).join("");$("#empty").hidden=a.length>0;document.querySelectorAll("[data-p]").forEach(x=>x.onclick=()=>project(x.dataset.p))}
async function project(id){PID=id;$("#home").hidden=true;$("#project").hidden=false;$("#back").hidden=false;$("#title").textContent="Obra";let p=await get();$("#ptype").textContent=p.type.toUpperCase();$("#pname").textContent=p.name;$("#paddress").textContent=p.address||"Sin dirección";$("#tabs").innerHTML=tabs.map(t=>`<button data-t=${t}>${t[0].toUpperCase()+t.slice(1)}</button>`).join("");document.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>show(b.dataset.t));show("resumen")}
function show(t){TAB=t;document.querySelectorAll("[data-t]").forEach(b=>b.classList.toggle("on",b.dataset.t===t));render()}
async function render(){let p=await get(),c=$("#content");if(TAB==="resumen"){let open=p.issues.filter(i=>i.status!=="Verificada"),sum=costs(p);c.innerHTML=`<div class=stats><div class=stat><span>Incidencias abiertas</span><strong>${open.length}</strong></div><div class=stat><span>Visitas</span><strong>${p.visits.length}</strong></div><div class=stat><span>Fotos</span><strong>${p.photos.length}</strong></div><div class=stat><span>Previsión final</span><strong>${eur(sum.forecast)}</strong></div></div><div class=box><h3>Pendiente de revisar</h3>${open.slice(0,6).map(i=>`<p><b>${esc(i.title)}</b><br><small>${esc(i.location)} · ${esc(i.trade)}</small></p>`).join("")||"<p>Sin incidencias pendientes.</p>"}</div><div class=box><h3>Acciones rápidas</h3><button onclick="add('visit')">＋ Visita</button> <button onclick="add('issue')">＋ Incidencia</button> <button onclick="photo()">＋ Foto</button> <button onclick="report()">Informe PDF</button></div>`;return}
let cfg={visitas:["Visitas de obra","visit","visits"],incidencias:["Incidencias","issue","issues"],mediciones:["Mediciones rápidas","measurement","measurements"],actas:["Actas y acuerdos","minute","minutes"],documentos:["Control documental","document","documents"],costes:["Control económico","cost","costs"]};
if(TAB==="fotos"){c.innerHTML=`<div class=toolbar><h3>Archivo fotográfico</h3><button onclick=photo()>＋ Foto</button></div><div class=photos>${p.photos.map(x=>`<div class=photo><img src="${x.data}"><div><b>${esc(x.title)}</b><br>${esc(x.location)} · ${date(x.date)}</div></div>`).join("")}</div>`;return}
let [title,type,key]=cfg[TAB],arr=p[key];c.innerHTML=`<div class=toolbar><h3>${title}</h3><button onclick="add('${type}')">＋ Añadir</button></div>`+(TAB==="costes"?costStats(p):"")+`<div class=cards>${arr.map(x=>card(type,x)).join("")||'<div class=empty>Sin registros todavía.</div>'}</div>`;document.querySelectorAll("[data-e]").forEach(x=>x.onclick=()=>edit(type,x.dataset.e))}
function card(t,x){if(t==="visit")return `<article class=card data-e=${x.id}><span class=badge>VISITA ${esc(x.number)}</span><h3>${date(x.date)}</h3><p>${esc(x.summary)}</p><div class=meta>${esc(x.attendees)}</div></article>`;if(t==="issue")return `<article class="card ${x.priority==="Alta"?"high":x.priority==="Baja"?"low":"medium"}" data-e=${x.id}><div class="issue-badges"><span class="badge ${x.status==="Verificada"?"verified":"pending"}">${x.status}</span><span class="badge priority-badge priority-${(x.priority||"Media").toLowerCase()}">PRIORIDAD ${esc((x.priority||"Media").toUpperCase())}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class=meta>${esc(x.location)} · ${esc(x.trade)} · ${x.due?date(x.due):"sin fecha límite"}</div></article>`;if(t==="measurement")return `<article class=card data-e=${x.id}><span class=badge>${esc(x.chapter)}</span><h3>${esc(x.name)}</h3><p class=measure>${Number(x.total).toLocaleString("es-ES")} ${x.unit}</p><div class=meta>${esc(x.location)}</div></article>`;if(t==="minute")return `<article class=card data-e=${x.id}><span class="badge ${x.done?"verified":"pending"}">${x.done?"Cerrado":"Pendiente"}</span><h3>${esc(x.topic)}</h3><p>${esc(x.agreement)}</p><div class=meta>${esc(x.responsible)} · ${date(x.due)}</div></article>`;if(t==="document")return `<article class=card data-e=${x.id}><span class="badge ${x.status==="Recibido"?"verified":"pending"}">${x.status}</span><h3>${esc(x.name)}</h3><p>${esc(x.category)}</p><div class=meta>${esc(x.responsible)}</div></article>`;return `<article class=card data-e=${x.id}><span class=badge>${x.type}</span><h3>${esc(x.description)}</h3><p class=measure>${eur(x.amount)}</p><div class=meta>${date(x.date)}</div></article>`}
function add(t){edit(t,null)}async function edit(t,id){let p=await get(),map={visit:"visits",issue:"issues",measurement:"measurements",minute:"minutes",document:"documents",cost:"costs"},x=id?p[map[t]].find(a=>a.id===id):{};let h="";
if(t==="visit")h=f("number","Número / referencia","text",x.number||"")+f("date","Fecha","date",x.date||today())+f("attendees","Asistentes","text",x.attendees||"")+f("summary","Resumen","textarea",x.summary||"")+f("observations","Observaciones","textarea",x.observations||"");
if(t==="issue")h=f("title","Título","text",x.title||"")+f("description","Descripción","textarea",x.description||"")+`<div class=grid2>${f("location","Ubicación","text",x.location||"")}${f("trade","Gremio / responsable","text",x.trade||"")}</div><div class=grid2>${f("priority","Prioridad","select",x.priority||"Media",["Baja","Media","Alta"])}${f("status","Estado","select",x.status||"Pendiente",["Pendiente","En curso","Corregida","Verificada"])}</div>`+f("due","Fecha límite","date",x.due||"");
if(t==="measurement")h=f("chapter","Capítulo","text",x.chapter||"")+f("name","Partida / concepto","text",x.name||"")+`<div class=grid2>${f("qty","Repeticiones","number",x.qty||1)}${f("unit","Unidad","select",x.unit||"m²",["ud","m","m²","m³","kg","l"])}</div><div class=grid2>${f("a","Dimensión A","number",x.a||1)}${f("b","Dimensión B","number",x.b||1)}</div>`+f("c","Dimensión C","number",x.c||1)+f("location","Ubicación","text",x.location||"");
if(t==="minute")h=f("topic","Asunto","text",x.topic||"")+f("agreement","Acuerdo / acción","textarea",x.agreement||"")+`<div class=grid2>${f("responsible","Responsable","text",x.responsible||"")}${f("due","Fecha límite","date",x.due||"")}</div>`+f("done","Estado","select",x.done?"Cerrado":"Pendiente",["Pendiente","Cerrado"]);
if(t==="document")h=f("name","Documento","text",x.name||"")+f("category","Categoría","select",x.category||"General",["General","Proyecto","Licencias","Calidad","Ensayos","Instalaciones","Seguridad","Final de obra","Garantías"])+f("status","Estado","select",x.status||"Pendiente",["Pendiente","Solicitado","Recibido"])+f("responsible","Responsable de aportar","text",x.responsible||"")+f("expiry","Caducidad","date",x.expiry||"");
if(t==="cost")h=f("type","Tipo","select",x.type||"Certificación",["Certificación","Modificado","Ajuste"])+f("description","Descripción","text",x.description||"")+f("amount","Importe (€)","number",x.amount||0)+f("date","Fecha","date",x.date||today());
openForm(id?"Editar registro":"Nuevo registro",h,{type:t,id,map:map[t]},!!id)}
async function save(fd){let d=Object.fromEntries(fd),p;if(CTX.type==="newproject"){p={id:uid(),name:d.name,address:d.address,type:d.type,start:d.start,client:d.client,contractor:d.contractor,technician:d.technician,notes:d.notes,budget:Number(d.budget||0),visits:[],issues:[],photos:[],measurements:[],minutes:[],documents:[],costs:[],updated:new Date().toISOString()};await put(p);$("#dlg").close();project(p.id);return}if(CTX.type==="editproject"){p=await get();Object.assign(p,d);p.budget=Number(d.budget||0);await put(p);$("#dlg").close();project(PID);return}
if(CTX.type==="photo-new"){p=await get();p.photos.push({id:uid(),data:CTX.data,title:d.title||"Fotografía de obra",location:d.location||"",note:d.note||"",date:today()});await put(p);$("#dlg").close();await render();toast("Fotografía guardada");return}
p=await get();let arr=p[CTX.map],old=CTX.id?arr.find(x=>x.id===CTX.id):{},x={...old,...d,id:old.id||uid()};if(CTX.type==="minute")x.done=d.done==="Cerrado";if(CTX.type==="cost")x.amount=Number(d.amount);if(CTX.type==="measurement"){["qty","a","b","c"].forEach(k=>x[k]=Number(d[k]||1));let dim=x.unit==="ud"?1:x.unit==="m"?x.a:x.unit==="m²"?x.a*x.b:x.unit==="m³"?x.a*x.b*x.c:x.a;x.total=x.qty*dim}if(CTX.id)arr[arr.findIndex(a=>a.id===CTX.id)]=x;else arr.push(x);await put(p);$("#dlg").close();render()}
async function del(){if(!confirm("¿Eliminar este registro?"))return;let p=await get(),a=p[CTX.map];a.splice(a.findIndex(x=>x.id===CTX.id),1);await put(p);$("#dlg").close();render()}
function pform(p={}){return f("name","Nombre de la obra","text",p.name||"")+f("address","Dirección","text",p.address||"")+`<div class=grid2>${f("type","Tipo","select",p.type||"Obra",["Obra","Reforma","Rehabilitación","Vivienda","Local","Industrial","Otro"])}${f("start","Fecha de inicio","date",p.start||today())}</div>`+f("client","Promotor / cliente","text",p.client||"")+f("contractor","Contratista principal","text",p.contractor||"")+f("technician","Técnico responsable","text",p.technician||"")+f("budget","Presupuesto base (€)","number",p.budget||0)+f("notes","Notas generales","textarea",p.notes||"")}
async function photo(){
  let i=document.createElement("input");
  i.type="file"; i.accept="image/*"; i.capture="environment";
  i.onchange=async()=>{
    const file=i.files&&i.files[0]; if(!file)return;
    try{
      const data=await compress(file);
      openForm("Guardar fotografía",
        `<div class="photo-preview-wrap"><img class="photo-preview" src="${data}" alt="Previsualización"></div>`+
        f("title","Título","text","Fotografía de obra")+
        f("location","Ubicación / zona","text","")+
        f("note","Observación","textarea",""),
        {type:"photo-new",data}
      );
    }catch(e){ alert("No se ha podido preparar la fotografía."); }
  };
  i.click();
}
function compress(file){return new Promise(ok=>{let r=new FileReader;r.onload=e=>{let im=new Image;im.onload=()=>{let w=im.width,h=im.height,k=Math.min(1,1400/Math.max(w,h));let c=document.createElement("canvas");c.width=w*k;c.height=h*k;c.getContext("2d").drawImage(im,0,0,c.width,c.height);ok(c.toDataURL("image/jpeg",.75))};im.src=e.target.result};r.readAsDataURL(file)})}
function toast(msg){let x=document.createElement("div");x.className="toast";x.textContent=msg;document.body.appendChild(x);requestAnimationFrame(()=>x.classList.add("show"));setTimeout(()=>{x.classList.remove("show");setTimeout(()=>x.remove(),250)},2200)}
function costs(p){let cert=0,chg=0;p.costs.forEach(x=>{if(x.type==="Certificación")cert+=+x.amount;if(x.type==="Modificado")chg+=+x.amount});return{budget:+p.budget||0,cert,chg,forecast:(+p.budget||0)+chg}}function costStats(p){let s=costs(p);return `<div class=stats><div class=stat><span>Presupuesto</span><strong>${eur(s.budget)}</strong></div><div class=stat><span>Certificado</span><strong>${eur(s.cert)}</strong></div><div class=stat><span>Modificados</span><strong>${eur(s.chg)}</strong></div><div class=stat><span>Previsto final</span><strong>${eur(s.forecast)}</strong></div></div>`}
async function report(){let p=await get(),open=p.issues.filter(i=>i.status!=="Verificada"),s=costs(p);$("#report").innerHTML=`<h1>${esc(p.name)}</h1><p>${esc(p.address)}<br>Informe: ${date(today())}<br>Técnico: ${esc(p.technician||"—")}</p><section class=rsec><h2>Resumen</h2><p>${p.visits.length} visitas · ${open.length} incidencias abiertas · ${p.photos.length} fotografías</p></section><section class=rsec><h2>Incidencias abiertas</h2>${open.map(i=>`<div class=ritem><b>${esc(i.title)}</b><p>${esc(i.description)}</p><small>${esc(i.location)} · ${esc(i.trade)} · ${i.status}</small></div>`).join("")||"Sin incidencias abiertas."}</section><section class=rsec><h2>Últimas visitas</h2>${[...p.visits].reverse().slice(0,10).map(v=>`<div class=ritem><b>${date(v.date)}</b><p>${esc(v.summary)}</p></div>`).join("")}</section><section class=rsec><h2>Acuerdos pendientes</h2>${p.minutes.filter(x=>!x.done).map(x=>`<div class=ritem><b>${esc(x.topic)}</b><p>${esc(x.agreement)}</p><small>${esc(x.responsible)} · ${date(x.due)}</small></div>`).join("")||"Sin acuerdos pendientes."}</section><section class=rsec><h2>Control económico</h2><p>Presupuesto ${eur(s.budget)} · Modificados ${eur(s.chg)} · Previsión ${eur(s.forecast)} · Certificado ${eur(s.cert)}</p></section><section class=rsec><h2>Fotografías</h2>${p.photos.slice(0,20).map(x=>`<div class=ritem><b>${esc(x.title)}</b><br><img class=rimg src="${x.data}"><p>${esc(x.location)} · ${esc(x.note)}</p></div>`).join("")}</section>`;setTimeout(()=>print(),100)}
$("#newProject").onclick=()=>openForm("Nueva obra",pform(),{type:"newproject"});$("#editProject").onclick=async()=>openForm("Editar obra",pform(await get()),{type:"editproject"});$("#close").onclick=()=>$("#dlg").close();$("#form").onsubmit=e=>{e.preventDefault();save(new FormData(e.target))};$("#del").onclick=del;$("#back").onclick=home;
$("#importFile").onchange=async e=>{try{let p=JSON.parse(await e.target.files[0].text());p.id=uid();p.name+=" (importada)";await put(p);home();alert("Copia importada.")}catch{alert("El archivo no es una copia válida.")}};
document.querySelector(".import").onclick=()=>$("#importFile").click();
(async()=>{await odb();home();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js")})();